# External service URLs for the Meteor Madness app
nasa_neo_feed_url: "https://api.nasa.gov/neo/rest/v1/feed"
openstreetmap_tile_url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
openstreetmap_attribution: "&copy; OpenStreetMap contributors"
city_image_url: "https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80"
